[package]
name = "poweroftwo"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0-alpha.2"
serde = { version = "1.0.215", features = ["derive"] }
ratatui = "0.29.0"
crossterm = "0.28.1"
serde_json = "1.0"
